# Generated by Django 3.2.7 on 2021-10-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_auto_20211010_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100)),
                ('objetivogeneral', models.TextField(max_length=5000)),
                ('modalidad', models.CharField(max_length=10)),
                ('costo', models.IntegerField()),
                ('horascatedra', models.IntegerField()),
                ('cantidadminalumnos', models.IntegerField()),
                ('cantidadmaxalumnos', models.IntegerField()),
                ('fechaini', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('docentecargo', models.ManyToManyField(to='usuarios.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=5000)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=30)),
                ('codcurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor')),
            ],
        ),
    ]
