# Generated by Django 3.2.7 on 2021-10-22 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fechaini',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
