# Generated by Django 3.2.7 on 2021-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_fechaini'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estadocurso',
            field=models.CharField(default='En Curso', max_length=20),
        ),
    ]
