# Generated by Django 3.2.7 on 2021-10-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_estadocurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial'), ('mixto', 'Mixto')], max_length=10),
        ),
    ]
