# Generated by Django 3.2.7 on 2021-10-24 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_modalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormaPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=15)),
                ('importe', models.IntegerField()),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(default=datetime.date.today)),
                ('numeroRecibo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormaPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=15)),
                ('importe', models.IntegerField()),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(default=datetime.date.today)),
                ('titularTarjeta', models.CharField(max_length=50)),
                ('numeroTarjeta', models.CharField(max_length=16)),
                ('TipoTarjeta', models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito')], max_length=10)),
                ('codSeguridad', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FormaPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], max_length=15)),
                ('importe', models.IntegerField()),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(default=datetime.date.today)),
                ('CBU', models.CharField(max_length=22)),
                ('alias', models.CharField(max_length=25)),
                ('banco', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
