# Generated by Django 3.2.7 on 2021-10-26 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_pagoefectivo_pagotarjeta_pagotransferencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoefectivo',
            old_name='FormaPago',
            new_name='formaPago',
        ),
        migrations.RenameField(
            model_name='pagotarjeta',
            old_name='FormaPago',
            new_name='formaPago',
        ),
        migrations.RenameField(
            model_name='pagotarjeta',
            old_name='TipoTarjeta',
            new_name='tipoTarjeta',
        ),
        migrations.RenameField(
            model_name='pagotransferencia',
            old_name='FormaPago',
            new_name='formaPago',
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='fechaCaducidad',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
