# Generated by Django 3.2.7 on 2021-10-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_estudiante_matricula'),
        ('cursos', '0006_auto_20211026_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoefectivo',
            name='numeroRecibo',
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='numRecibo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='numeroTicket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='numRecibo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagotransferencia',
            name='numRecibo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagoefectivo',
            name='formaPago',
            field=models.CharField(default='Efectivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagoefectivo',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='formaPago',
            field=models.CharField(default='PagoTarjeta', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pagotransferencia',
            name='formaPago',
            field=models.CharField(default='PagoTransferencia', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagotransferencia',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='Inscriptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.IntegerField(null=True)),
                ('nota2', models.IntegerField(null=True)),
                ('nota3', models.IntegerField(null=True)),
                ('asistencia', models.CharField(max_length=4)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('incriptos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante')),
            ],
        ),
    ]
