# Generated by Django 3.2.7 on 2021-10-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_auto_20211028_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoefectivo',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pagotarjeta',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pagotransferencia',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
