# Generated by Django 3.2.7 on 2021-11-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20211028_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='honorarios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
