# Generated by Django 3.2.7 on 2021-11-02 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_curso_honorarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estadocurso',
            field=models.CharField(choices=[('en_revision', 'EN Revision'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='En Revision', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fechafin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fechaini',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='propuesta',
        ),
    ]
