# Generated by Django 3.2.7 on 2021-11-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_auto_20211102_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='motivo',
            field=models.TextField(default='Sin Motivo', max_length=1000),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estadocurso',
            field=models.CharField(choices=[('en_revision', 'En Revision'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='En Revision', max_length=20),
        ),
    ]
