# Generated by Django 3.2.7 on 2021-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_auto_20211102_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscriptos',
            old_name='incriptos',
            new_name='inscripto',
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='asistencia',
            field=models.CharField(default='100%', max_length=4),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='nota1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='nota2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='nota3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
