# Generated by Django 3.2.7 on 2021-11-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_auto_20211104_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptos',
            name='nota1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='nota2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='nota3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
