# Generated by Django 3.2.7 on 2021-11-05 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20211104_2333'),
        ('cursos', '0013_auto_20211104_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptos',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='inscriptos',
            name='inscripto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante'),
        ),
    ]
