# Generated by Django 3.2.7 on 2021-11-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20211105_1023'),
        ('cursos', '0014_auto_20211104_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoefectivo',
            name='curso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='pagoefectivo',
            name='inscripto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='curso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='inscripto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='pagotransferencia',
            name='curso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='pagotransferencia',
            name='inscripto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante'),
        ),
    ]
