# Generated by Django 3.1 on 2021-11-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_auto_20211111_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fechaini',
            field=models.DateField(),
        ),
    ]
