# Generated by Django 3.2.7 on 2021-10-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombreyapellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.IntegerField()),
                ('sexo', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=256)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('matricula', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombreyapellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.IntegerField()),
                ('sexo', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=256)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('fechaIngresoTrabajar', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
            ],
        ),
    ]
