# Generated by Django 3.2.7 on 2021-10-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='titulo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='titulo',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
