# Generated by Django 3.2.7 on 2021-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211010_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
