# Generated by Django 3.2.7 on 2021-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211022_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
