# Generated by Django 3.2.7 on 2021-10-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_estudiante_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otrxs', 'Otrxs')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otrxs', 'Otrxs')], max_length=15),
        ),
    ]
