# Generated by Django 3.2.7 on 2021-11-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20211104_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='rol',
        ),
    ]
